/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`
// Run `pnpm generate:types:cloudflare` to regenerate this file
declare namespace Cloudflare {
  interface Env {
    DB: D1Database // Matches the binding name in wrangler.toml
    // Add other bindings here as needed (R2, KV, etc.)
  }
}
interface CloudflareEnv extends Cloudflare.Env {}
